spring:
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:seed_data.sql
      continue-on-error: false